spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/java-todo-api"
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: utf-8
    initialization-mode: always
